-- ============================================================
-- VENDOR MASTER DATA
-- OR number present = VAT registered
-- ============================================================

INSERT INTO "Vendors" (tenant_id, name, address, tin, is_vat_registered, is_deleted, created_at, updated_at)
VALUES
((SELECT id FROM "Tenants" LIMIT 1), 'Aethan Fruit And Vegetable Stall', 'CORONG-CORONG, EL NIDO', '733-131-504-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Amarah & Toni Frozen Products Stor', 'VILLA LIBERTAD, EL NIDO', '621-604-112-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Angel Store', '', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Arm Glass', 'El Nido, Palawan', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Aveline Jay Store', 'VILLA LIBERTAD, EL NIDO', '707-992-833-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Ayala Land, Inc.', 'Makati, Metro Manila', '000-477-863-000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Banwa BMCS', 'El Nido, Palawan', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Canva', 'Online', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Chenchen Meat Shop', 'LIO MARKET', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Cherimakar Marketing Corporation', 'BUENA SUERTE, EL NIDO', '007-937-817-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Cris Store', 'VILLA LIBERTAD, EL NIDO', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Deborde Electronics Ref''N,Airconditioning Svs.', 'MASAGANA, EL NIDO', '715-036-816-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Dryft Fish Trading', 'CORONG-CORONG, EL NIDO', '330-218-473-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Estremera Store', 'LAMORO, EL NIDO', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Glenda Alagos', 'El Nido, Palawan', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Globe Telecom', '', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Green Market El Nido', 'VILLA LIBERTAD, EL NIDO', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Green Market Fruit And Vegetable Trading', 'BAGUIO CITY,BENGUET', '263-475-441-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Haydako Water Station', 'VILLA LIBERTAD, EL NIDO', '449-925-777-00004', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Humans Serving Humans Nutrition Inc.', 'VILLA LIBERTAD, EL NIDO', '678-071-883-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Imana & Matt', '', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Instagram / Meta', 'Online', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'J&V Trading', 'EL NIDO', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'LICK Coffee', 'El Nido, Palawan', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Lamoro Hill Bakery', 'Lamoro, El Nido', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Lazada', 'Online', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Lost Islands Center For Kape Inc.', 'MALIGAYA, EL NIDO', '770-552-171-000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Masa Bakehouse', 'El Nido, Palawan', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Meatlandia Meat Shop', 'MALIGAYA, EL NIDO', '401-097-188-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Mercury Drug - El Nido', 'Villa Libertad, El Nido', '004-461-256-00071', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Mr. G', 'Lio Estate, El Nido', '', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Newmak Convenience Store', 'CORONG-CORONG, EL NIDO', '669-633-235-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Nutrifinds', '', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Ola Granola', '', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Ola Palawan', 'El Nido, Palawan', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Perpet Pilipinas Corp.', 'BAROTUAN, EL NIDO', '008-578-970-00076', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Perpet Pilipinas Inc.', 'BUCANA, EL NIDO', '008-578-970-00074', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Prince Princessisa Inc.', 'MALIGAYA, EL NIDO', '445-049-769-00005', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Puerto Delicatessen Food Products', 'CORONG-CORONG, EL NIDO', '131-052-392-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Rala Lpg And Lpg Accessories Trading', 'MALIGAYA, EL NIDO', '931-414-575-00001', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Shein', 'Online', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Spotify', 'Online', '', false, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'The Italian Food Specialists, Inc.', 'MASAGANA, EL NIDO', '006-917-492-008', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'William Tan Enterprises, Inc.', 'CORONG-CORONG, EL NIDO', '007-793-938-00013', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Xtramile Dipnay Gasoline Station', 'SAN FERNANDO, EL NIDO', '701-717-232-00000', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Y.C. Echague Corporation', 'BUENA SUERTE, EL NIDO', '009-797-687-00002', true, false, now(), now()),
((SELECT id FROM "Tenants" LIMIT 1), 'Zay-An Store', '', '', false, false, now(), now())
ON CONFLICT DO NOTHING;
